version: "3.9"

services:
  db:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    env_file:
      - .env

  webapp:
    image: node:lts
    container_name: nuxt
    command: yarn dev
    volumes:
      - ./webapp:/usr/src/app
    working_dir: /usr/src/app
    environment:
      HOST: 0.0.0.0
    depends_on:
      - api
    network_mode: host
    env_file:
      - .env

  api:
    container_name: flask
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/usr/src/app
    command: python run.py
    network_mode: host
    environment:
      HOST: 0.0.0.0
    depends_on:
      - db
    env_file:
      - .env

volumes:
  mongodata: