version: "3.9"

services:
  db:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: fedabian
    volumes:
      - mongodata:/data/db

  webapp:
    image: node:latest
    container_name: nuxt
    command: npm run dev
    volumes:
      - ./webapp:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    environment:
      HOST: 0.0.0.0

  api:
    container_name: flask
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/usr/src/app
    command: python run.py
    ports:
      - 5000:5000
    environment:
      HOST: 0.0.0.0
    links:
      - db

volumes:
  mongodata:
